/**
 * English translation — the English for every `t("…")` sentence.
 *
 * `i18n-check.mjs` looks for each `t("…")` sentence in here; anything missing
 * will show Hindi in the app and turn the check red. So every sentence here
 * must be complete.
 *
 * Source: D:\bajrang\src\** — Hindi is the source language.
 */

export const EN: Record<string, string> = {
  "Bajrang को फ़ोन में लगाएँ": "Add Bajrang to your phone",
  "Safari → साझा करें → 'Add to Home Screen'": "Safari → Share → 'Add to Home Screen'",
  "एक टैप में खुलेगा, और रोज़ का संदेश भी आएगा।": "It opens in one tap, and the daily message comes too.",
  "लगाएँ": "Install",
  "ठीक है": "Okay",
  "दिन": "days",
  "भक्त": "Devotee",
  "तस्वीर सहेजी जा रही है — फिर WhatsApp में चुन लीजिए।": "The image is being saved — then choose it in WhatsApp.",
  "पॉपअप ब्लॉक है — तस्वीर सहेजें दबाएँ।": "A pop-up is in the way — press Save image.",
  "बजरंग कार्ड": "Bajrang card",
  "तस्वीर खुल गई — लंबे दबाएँ और 'Save Image' चुनें।": "The image has opened — press and hold, then choose 'Save Image'.",
  "बात कॉपी हो गई।": "The message has been copied.",
  "कॉपी नहीं हो सका।": "Could not copy.",
  "साप्ताहिक कार्ड": "Weekly card",
  "बंद करें": "Close",
  "बजरंग साप्ताहिक कार्ड": "Bajrang weekly card",
  "तैयार हो रहा है…": "Preparing…",
  "साझा करें": "Share",
  "WhatsApp पर भेजें": "Send on WhatsApp",
  "तस्वीर सहेजें": "Save the image",
  "तस्वीर खोलें": "Open the image",
  "PNG तस्वीर · 1080 × 1080 · कोई ऐप नहीं, सीधे WhatsApp": "PNG image · 1080 × 1080 · no app needed, straight to WhatsApp",
  "सिर्फ़ बात कॉपी करें": "Copy the message only",
  "हनुमान जी का वार है — आज की पूजा 1 मिनट में पूरी करो": "Hanuman ji has come — finish today's worship in 1 minute",
  "जय बजरंगबली 🙏": "Jai Bajrang Bali 🙏",
  "बजरंग": "Bajrang",
  "हर दिन 1 मिनट की हनुमान पूजा": "1 minute of Hanuman worship every day",
  "मैंने {p} लगातार हनुमान चालीसा की": "I have recited the Hanuman Chalisa {p} in a row",
  "संकल्प:": "Sankalp:",
  "चलो हनुमान जी के साथ जियें": "Come, let us stay with Hanuman ji",
  "मैंने {p} लगातार हनुमान चालीसा की 🙏": "I have recited the Hanuman Chalisa {p} in a row 🙏",
  "आज का स्ट्रीक:": "Today's streak:",
  "मेरा संकल्प:": "My sankalp:",
  "आप भी रोज़ 1 मिनट हनुमान जी के साथ बिताइए — Bajrang app": "You too, spend 1 minute each day with Hanuman ji — Bajrang app",
  "पिछला महीना": "Previous month",
  "अगला महीना": "Next month",
  "मंगलवार / शनिवार": "Tuesday / Saturday",
  "पूजा पूरी": "Worship complete",
  "आज": "Today",
  "इस महीने पर लौटें": "Back to this month",
  "मंगलवार": "Tuesday",
  "— हनुमान जी का प्रिय दिन": " — Hanuman ji's beloved day",
  "शनिवार": "Saturday",
  "— संकष्टी, हनुमान जी के लिए समर्पित": " — purna, dedicated to Hanuman ji",
  "हर हफ़्ते दो बार संकल्प दोहराना आसान है — बस एक मिनट।": "Repeating your sankalp twice a week is easy — just one minute.",
  "स्रोत:": "Source:",
  "स्रोत देखें": "See the source",
  "अपने इलाके के पंचांग या धर्मप्रधान से भी तिथि जाँच लीजिए — पंचांग हर जगह एक जैसा नहीं होता।": "You can also check the date with your local Panchang or with your religious head — the Panchang is not the same everywhere.",
  "हनुमान जी के दिन": "Hanuman ji's days",
  "त्योहार की तिथि": "Festival date",
  "पंचांग": "Panchang",
  "आने वाला त्योहार": "Upcoming festival",
  "ये तिथियाँ": "These dates",
  "नया शुरुआत": "A new beginning",
  "विश्राम": "Pause",
  "जय श्री राम": "Jai Shri Ram",
  "आज की पूजा पूरी हो चुकी है। शाम को फिर मिलेंगे।": "Today's worship is complete. We will meet again this evening.",
  "आज का एक मिनट, हनुमान जी के साथ।": "One minute today, with Hanuman ji.",
  "है — हनुमान जी के दिन। आज का पूजा और सोहना है।": " is — a day of Hanuman ji. Today there is worship, and there is adornment.",
  "आज की पूजा पूरी 🙏": "Today's worship is complete 🙏",
  "कल फिर मिलेंगे। हनुमान जी आपका रक्षक हैं।": "We will meet again tomorrow. Hanuman ji is your protector.",
  "साप्ताहिक कार्ड साझा करें": "Share the weekly card",
  "आज की पूजा शुरू करें": "Begin today's worship",
  "साप्ताहिक कार्ड बनाएँ": "Create the weekly card",
  "आज रविवार है · Sunday": "Today is Sunday · Sunday",
  "आपके {n} दिन की साधना को साझा करें — एक तस्वीर, कुछ लोगों के लिए प्रेरणा बन जाएगी।": "Share your {n} days of sadhana — one picture can become inspiration for someone.",
  "विश्राम जारी है": "Pause is still on",
  "और आराम। आपकी {n} दिन की साधना जहाँ थी वहीं सुरक्षित है — रुके हुए दिन छूटे नहीं गिने जाएँगे। जब मन करे, पूजा कीजिए।": "and more rest. Your {n} days of sadhana stay safe where they were — paused days will not be counted as missed. Worship whenever your heart feels like it.",
  "आज विश्राम का अंतिम दिन है। कल फिर सिलसिला यहीं से आगे बढ़ेगा।": "Today is the last day of the pause. Tomorrow the chain moves on from here.",
  "आज से फिर शुरू करें": "Begin again from today",
  "क्षमा बचा लेगी": "Grace will cover it",
  "{m} दिन छूट गए हैं, पर आपके पास": "{m} days have slipped away, but you still have",
  "क्षमा दिन": "grace days",
  "हैं। आज पूजा कीजिए — सिलसिला टूटेगा नहीं। कोई डाँट नहीं, बस ध्यान रखिए।": "left. Worship today — the chain will not break. No scolding, just stay careful.",
  "चिंता मत करो, फिर से शुरू करो 🙏": "Do not worry, begin again 🙏",
  "दिन बीत गए": "Days have passed",
  "({n} — कोई बात नहीं। हनुमान जी आज भी आपके साथ हैं। एक मिनट से ही सब शुरू हो जाता है।": "({n} — it is nothing. Hanuman ji is with you today as well. One minute is all it takes to begin again.",
  "बजरंग कथा": "The Bajrang Katha",
  "आज का श्लोक": "Today's verse",
  "आज का संदेश": "Today's message",
  "आपका संकल्प": "Your sankalp",
  "साप्ताहिक सारांश": "Weekly summary",
  "इस हफ़्ते": "This week",
  "कुल पूजा": "Total worship",
  "सर्वश्रेष्ठ": "Best",
  "क्षमा दिन बाकी": "Grace days left",
  "हर {n} दिन की साधना पर एक क्षमा दिन मिलता है (ज़्यादा से ज़्यादा {m})। दिन छूट जाए तो अपने आप लग जाती है।": "Every {n} days of sadhana bring one grace day (at most {m}). If a day is missed, it is applied on its own.",
  "जय बजरंगबली 🙏 — प्रेम और अनुशासन, रोज़ एक मिनट": "Jai Bajrang Bali 🙏 — love and discipline, one minute a day",
  "आज की पूजा के बाद खुलेगा पहला प्रसंग": "The first passage opens after today's worship",
  "रोज़ एक प्रसंग, पूजा के बाद — ताकि कथा आगे बढ़ती रहे और आप कल फिर आएँ।": "One passage a day, after worship — so the Katha keeps moving forward and you come back tomorrow.",
  "कथा देखें": "Read the Katha",
  "सौ आठ प्रसंग पूरे": "All 108 passages done",
  "आप पूरी कथा सुन चुके हैं। हनुमान जी का साथ सदा के लिए बना रहे।": "You have heard the whole Katha. May Hanuman ji's company stay with you always.",
  "कथा दोबारा पढ़ें": "Read the Katha again",
  "कल पूजा के बाद खुलेगा — प्रसंग {n}: {title}।": "Opens tomorrow after worship — passage {n}: {title}.",
  "कथा पढ़ें": "Read the Katha",
  "शुभ रात्रि 🙏": "Good night 🙏",
  "शुभ प्रभात 🙏": "Good morning 🙏",
  "नमस्कार 🙏": "Namaste 🙏",
  "शुभ संध्या 🙏": "Good evening 🙏",
  "रोज़ सुबह का संदेश चालू करें?": "Turn on the morning message?",
  "आपके चुने हुए समय पर हनुमान जी का वार याद दिला देंगे — हर दिन सिर्फ़ एक बार।": "We will remind you of Hanuman ji's arrival at the time you have chosen — only once a day.",
  "सेटिंग में जाएँ": "Go to Settings",
  "बाद में": "Later",
  "प्रसंग": "Passage",
  "कथा आरंभ": "The Katha begins",
  "पिछला प्रसंग": "Previous passage",
  "नया खुला प्रसंग": "New passage opened",
  "कल पूजा के बाद खुलेगा": "Opens tomorrow after worship",
  "सौ आठ प्रसंग पूरे हो गए। हनुमान जी का साथ अब भी साथ है 🙏": "All 108 passages are done. Hanuman ji's company is still with you 🙏",
  "रोज़ एक प्रसंग — पूजा के बाद ही खुलता है।": "One passage a day — it opens only after worship.",
  "आगे की कथा लिखी जा रही है — जिस दिन आपकी पूजा होगी, उसी दिन अगला प्रसंग खुल जाएगा।": "The next part of the Katha is being written — on the day you worship, the next passage will open.",
  "यह कथा रामचरितमानस की कथा-परंपरा पर आधारित है — सरल हिन्दी में, क्रम से। प्रारूप में लिखी गई है; मूल ग्रंथ से मिलाकर समीक्षा बाकी है।": "This Katha follows the katha tradition of Ramcharitmanas — in plain language, in order. It is written in draft form; a review against the original text is still to come.",
  "सीख · ": "Lesson · ",
  "परंपरा में मतभेद · ": "A difference of tradition · ",
  "यह प्रसंग अभी लिखा जा रहा है। जिस दिन आपकी पूजा होगी, उसी दिन यह पूरा खुल जाएगा।": "This passage is still being written. On the day you worship, it will open fully.",
  "रोज़ एक मिनट": "One minute a day",
  "जय बजरंगबली": "Jai Bajrang Bali",
  "हर रोज़ सिर्फ़ एक मिनट — हनुमान चालीसा का एक पंक्ति, एक घंटी, और आपका संकल्प।": "Every day only one minute — one line of the Hanuman Chalisa, one bell, and your sankalp.",
  "कोई नाम पहले नहीं चाहिए, कोई खाता नहीं।": "No name is needed first, and no account either.",
  "पूजा शुरू करें 🙏": "Begin worship 🙏",
  "आपका नाम और संकल्प पूजा के बाद पूछा जाएगा।": "Your name and sankalp will be asked after the worship.",
  "आज की पूजा": "Today's worship",
  "आवाज़ के साथ, या बिना?": "With sound, or without?",
  "दोनों ही बराबर हैं। जो मन को भाए, वही चुनिए।": "Both are equal. Choose whatever your heart likes.",
  "आवाज़ के साथ": "With sound",
  "बिना आवाज़": "Without sound",
  "अभी नहीं": "Not now",
  "आवाज़ बंद करें": "Turn sound off",
  "आवाज़ चालू करें": "Turn sound on",
  "मैंने जप पूरा कर लिया": "I have completed the jap",
  "पूजा पूरी!": "Worship complete!",
  "हनुमान जी आपके साथ हैं": "Hanuman ji is with you",
  "आपकी लगातार पूजा": "Your steady worship",
  "कुल": "Total",
  "पूजा पूर्ण": "worships complete",
  "नया बैज!": "New badge!",
  "होम पर जाएँ": "Go to Home",
  "पूजा पूरी! 🙏": "Worship complete! 🙏",
  "हनुमान जी ने आपका नाम जान लिया। वे हर दिन आपको याद करेंगे।": "Hanuman ji has taken note of your name. He will remember you every day.",
  "आपका नाम": "Your name",
  "सहेजें": "Save",
  "रहने दीजिए": "Leave it",
  "एक संकल्प रख लीजिए": "Keep a sankalp",
  "यह कोई बात नहीं — पर रोज़ याद आएगा।": "It is nothing — but it will come back to you daily.",
  "जैसे: परीक्षा में पास होना": "For example: passing my exam",
  "रोज़ किस समय याद करें?": "What time should I remind you each day?",
  "याद दिलाना चालू करें": "Turn on the reminder",
  "बाद में करूँगा": "I will do it later",
  "आज का नया प्रसंग": "Today's new passage",
  "यह प्रसंग अभी लिखा जा रहा है।": "This passage is still being written.",
  "पूरा प्रसंग पढ़ें": "Read the full passage",
  "संकल्प": "Sankalp",
  "जैसे: परिवार का स्वास्थ्य": "For example: my family's health",
  "रद्द": "Cancel",
  "संकल्प बदलें": "Change sankalp",
  "अभी कोई संकल्प नहीं": "No sankalp yet",
  "एक छोटा इरादा रखिए — पढ़ाई, सेहत, परिवार, कुछ भी। रोज़ याद आएगा, और पूजा का मक़सद साफ़ हो जाएगा।": "Keep a small intention — studies, health, family, anything at all. It will come back to you daily, and the purpose of worship will become clear.",
  "जितनी लंबी स्ट्रीक, उतना चमकता दीवा": "The longer the streak, the brighter the diya",
  "अगला बैज: {m} दिन — {r} दिन और।": "Next badge: {m} days — {r} more days.",
  "108 दिन पूरे — आप परम भक्त हैं!": "108 days complete — you are a true devotee!",
  "कुछ दिन छूट जाएँ तो कोई बात नहीं — चिंता मत करो, फिर से शुरू करो 🙏": "If a few days are missed, it is nothing — do not worry, begin again 🙏",
  "लगातार दिन": "Days in a row",
  "बैज": "Badges",
  "दीवे की चमक": "Brightness of the diya",
  "आपकी साधना": "Your sadhana",
  "हर दिन सुबह लग गया — ऐप बंद होने पर भी आएगा।": "It has been set for every morning — it will come even when the app is closed.",
  "इजाज़त मिली, पर समय नहीं लग सका।": "Permission was given, but the time could not be set.",
  "चालू — रोज़ सुबह संदेश आएगा।": "On — the message will come every morning.",
  "ब्राउज़र ने इजाज़त नहीं दी। फ़ोन की अलार्म में समय लगा लीजिए।": "The browser did not give permission. Set the time in your phone's alarm.",
  "https पर यह काम करता है। फ़ोन की अलार्म में समय लगा लीजिए।": "This works over https. Set the time in your phone's alarm as well.",
  "बंद कर दिया।": "It has been switched off.",
  "संदेश भेज दिया — देखिए।": "Message sent — have a look.",
  "संदेश नहीं जा सका।": "The message could not be sent.",
  "सेटिंग": "Settings",
  "सुरक्षित कनेक्शन नहीं है": "Not a secure connection",
  "अभी यह ऐप": "Right now this app",
  "पर चल रहा है। रोज़ का संदेश, फ़ोन में इंस्टॉल, और पूजा के दौरान स्क्रीन जली रखना — ये सब": "is running on. The daily message, install on your phone, and keeping the screen awake during worship — all of these need",
  "पर ही चलते हैं। पूजा और स्ट्रीक फिर भी ठीक से काम करेंगे।": "only. Worship and the streak will still work fine.",
  "असली जाँच के लिए ऐप को किसी https पते पर चलाएँ, या अपने फ़ोन के अलार्म में": "For a real test, run the app on an https address, or in your phone's alarm",
  "लगा लीजिए।": "have it set.",
  "याद दिलाना चालू रखें": "Keep the reminder on",
  "समय:": "Time:",
  "हर दिन": "Every day",
  "हर दिन लगा हुआ है।": "It is set for every day.",
  "ऐप बंद हो, फ़ोन बंद हो, कुछ भी हो — संदेश आ जाएगा।": "App closed, phone off, anything at all — the message will come.",
  "चालू है, पर समय नहीं लगा।": "It is on, but the time is not set.",
  "ऐप एक बार खोलिए, समय दोबारा चुनिए।": "Open the app once, choose the time again.",
  "ऐप बंद होने पर भी संदेश आएगा — यही Android ऐप की सबसे बड़ी बात है।": "The message comes even when the app is closed — this is the greatest thing about the Android app.",
  "Android से ठीक समय पर संदेश देने की अनुमति माँगी ज़रूरी है": "Android needs permission to deliver the message on time",
  "बिना इसके फ़ोन संदेश देर से दिखा सकता है।": "Without this, the phone may show the message late.",
  "Android सेटिंग्स में \"Alarms & reminders\" खोलिए।": "Open \"Alarms & reminders\" in Android Settings.",
  "अनुमति देने के लिए खोलें": "Open to give permission",
  "अपना समय चुनें": "Choose your time",
  "ऐसा संदेश आएगा": "A message like this will arrive",
  "अभी संदेश भेजकर देखें": "Send a test message now",
  "पहले ऊपर वाला स्विच चालू कीजिए — फिर यह संदेश जाँच सकेंगे।": "First turn on the switch at the top — then you can test this message.",
  "यह जाँच https पर ही हो पाएगी।": "This check will only work on https.",
  "यह संदेश Android के अलार्म पर लगा है — ऐप बंद होने पर भी आएगा। बस फ़ोन में": "This message is set on the Android alarm — it will come even when the app is closed. Just make sure",
  "से Bajrang को अनुमति दी हो तो ठीक समय आएगा।": "has permission on your phone, then it will arrive at the right time.",
  "यह PWA संस्करण है। ब्राउज़र बंद होने पर संदेश नहीं आ पाता, इसलिए भरोसेमंद नहीं।": "This is the PWA version. When the browser is closed the message does not arrive, so it cannot be relied on.",
  "Android ऐप": "Android app",
  "में यह हर दिन, ऐप बंद होने पर भी आता है — और वीडियो पर वही नाम, वही संदेश, वही स्ट्रीक चलती है। सबसे भरोसेमंद तरीका अभी भी:": "gives you this every day, even when the app is closed — and the same name, the same message, the same streak run on the video. The most dependable way is still:",
  "फ़ोन की अलार्म में भी": "an alarm in your phone at",
  "कभी-कभी बीमारी, यात्रा, या कोई मजबूरी होती है। ऐसे समय में डाँटने की बजाय रुक लीजिए — आपकी साधना जहाँ थी वहीं जुकी रहेगी। रुके हुए दिन छूटे नहीं गिने जाएँगे।": "Sometimes there is illness, travel, or some unavoidable reason. At such times, pause instead of blaming yourself — your sadhana stays joined where it was. Paused days will not be counted as missed.",
  "{d} दिन और। सिलसिला {s} दिन पर जुका हुआ है।": "{d} more days. Your chain is joined at {s} days.",
  "आज अंतिम दिन है।": "Today is the last day.",
  "विश्राम समाप्त। फिर शुरू करें 🙏": "Pause over. Begin again 🙏",
  "अभी लौटें": "Return now",
  "{d} दिन का विश्राम। आराम करिए।": "A pause of {d} days. Rest well.",
  "बाकी": "left",
  "हर {n} दिन लगातार पूजा करने पर एक क्षमा दिन अपने आप मिलता है। दिन छूट जाए तो यह अपने आप लग जाती है — इसलिए बार-बार सिलसिला नहीं टूटता।": "After {n} days of continuous worship, one grace day comes on its own. If a day is missed, it applies on its own — so your chain does not keep breaking.",
  "रात 3:00 बजे": "3:00 in the night, the day",
  "से शुरू होता है। रात 2 बजे की पूजा पहले दिन की गिनी जाती है — जैसे परंपरा में भी तिथि सूर्योदय से चलती है।": "begins then. Worship at 2 in the morning counts towards the previous day — as in tradition, the tithi also turns with sunrise.",
  "अभी पूजा का दिन है:": "Right now the worship day is:",
  "— घड़ी के हिसाब से": " — by the clock",
  "की रात है, पर पूजा का दिन पिछला ही चल रहा है।": "night, but the worship day is still the earlier one.",
  "पूजा के दौरान हल्का ॐ मंत्र": "a soft ॐ chant during worship",
  "बहुत धीमी, बहुत हल्की आवाज़ — साँस जैसी। पूजा के दौरान 🔊 बटन से भी बंद/चालू कर सकते हैं।": "A very slow, very soft sound — like a breath. During worship you can also turn it off and on with the 🔊 button.",
  "श्रीरामचरितमानस की भाषा में": "In the language of Shri Ramcharitmanas",
  "हिंदी में श्लोक उसी मूल रूप में रहते हैं": "in English the verses stay in their original form",
  "स्ट्रीक": "Streak",
  "सारी जानकारी सिर्फ़ आपके फ़ोन में सहेजी है — कोई अकाउंट नहीं, कोई सर्वर नहीं।": "All the information is stored only on your phone — no account, no server.",
  "रोज़ एक मिनट की पूजा, बस इतनी सी।": "One minute of worship a day, only that much.",
  "सारी जानकारी मिट जाएगी — नाम, संकल्प और स्ट्रीक। क्या आप नया शुरुआत करना चाहते हैं?": "All the information will be erased — your name, your sankalp and your streak. Do you want to start fresh?",
  "हाँ, नया शुरुआत करें": "Yes, start fresh",
  "नहीं": "No",
  "सब कुछ मिटाएँ": "Erase everything",
  "रोज़ का संदेश": "Daily message",
  "दिन की शुरुआत": "Start of the day",
  "पूजा की आवाज़": "Worship sound",
  "भाषा": "Language",
  "ऐप के बारे में": "About the app",
  "बाल्य": "Childhood",
  "संयम और साधना": "Restraint and sadhana",
  "लंका और समुद्र": "Lanka and the sea",
  "राम और सुग्रीव की मित्रता": "The friendship of Ram and Sugriv",
  "बाँध और सेना": "The bridge and the army",
  "लंका की चौथी रात": "The fourth night of Lanka",
  "महायुद्ध": "The great war",
  "विजय और लौटना": "Victory and the return",
  "आशीर्वाद": "Blessing",
  "आज ही है! 🙏": "Today itself! 🙏",
  "Drik Panchang · drikpanchang.com · शुक्ल नवमी, चैत्र": "Drik Panchang · drikpanchang.com · Shukla Navami, Chaitra",
  "Drik Panchang · drikpanchang.com · चैत्र पूर्णिमा": "Drik Panchang · drikpanchang.com · Chaitra Purnima",
  "भारत के पंचांग में गुरुवार 15 अप्रैल 2027। अमेरिका/यूरोप में यही तिथि 14 अप्रैल पड़ सकती है।": "In the Indian Panchang: Thursday 15 April 2027. In America/Europe the same tithi may fall on 14 April.",
  "उत्तर भारत की परंपरा — चैत्र पूर्णिमा, मंगलवार 20 अप्रैल 2027।": "North Indian tradition — Chaitra Purnima, Tuesday 20 April 2027.",
  "उत्तर भारत की परंपरा — चैत्र पूर्णिमा, शनिवार 8 अप्रैल 2028।": "North Indian tradition — Chaitra Purnima, Saturday 8 April 2028.",
  "भारत के पंचांग में सोमवार 3 अप्रैल 2028।": "In the Indian Panchang: Monday 3 April 2028.",
  "• चैत्र पूर्णिमा (हनुमान जयंती): drikpanchang.com/vrats/purnimasidates.html": "• Chaitra Purnima (Hanuman Janm): drikpanchang.com/vrats/purnimasidates.html",
  "• राम नवमी: drikpanchang.com/hindu-festivals/rama-navami": "• Rama Navami: drikpanchang.com/hindu-festivals/rama-navami",
  /* ---------- dynamic lists (navigation, sankalp ideas) ---------- */
  कथा: "Katha",
  Home: "Home",
  Katha: "Katha",
  Calendar: "Calendar",
  Sankalp: "Sankalp",
  Settings: "Settings",
  "परीक्षा में पास होना": "Passing my exam",
  "परिवार का स्वास्थ्य": "My family's health",
  "नौकरी मिलना": "Finding a job",
  "शांति और सच्चाई": "Peace and truth",
  "माँ-पापा की सेहत": "My parents' health",

  /* ---------- badges ---------- */
  "एक हफ़्ते की लगातार साधना। बहुत बढ़िया शुरुआत!":
    "One week of steady sadhana. A lovely beginning!",
  "तीन हफ़्ते। अब यह आपकी दिनचर्या बन गई।":
    "Three weeks. Now it has become part of your daily routine.",
  "108 — चालीसा के बारह आयाम। हनुमान जी की पूर्ण कृपा।":
    "108 — the twelve forms of the Chalisa. The full grace of Hanuman ji.",

  /* ---------- closing pairs ---------- */
  "दिन बाकी": "days left",
  पंक्ति: "Line",
  जप: "Jap",
  "सेकंड बाकी": "seconds left",
  "(drikpanchang.com) से ली गई हैं। भारत के पंचांग के हिसाब से चाँद वाले त्योहार एक दिन ऊपर-नीचे हो सकते हैं, और दूसरे देशों में यही तिथि एक दिन पहले पड़ सकती है। अपने इलाके की पंचांग से मिलाकर ऊपर वाली तारीख बदल दीजिए।":
    "are taken from (drikpanchang.com). In the Indian Panchang, moon-based festivals can fall a day earlier or later, and in other countries the same tithi may come a day sooner. Check it against the Panchang of your own region and change the date above if needed.",

  /* ---------- version line ---------- */
  "हिंदी ⇄ बंगाला": "English ⇄ Bengali",

  /* ---------- language-specific note (third language) ---------- */
  "English screen, but the verses stay in the original Devanagari":
    "English screen, but the verses stay in the original Devanagari",

  /* ---------- पंक्तियों की जाँच दिखाना ---------- */
  "जाँच बाकी": "Not checked yet",
  "यह पंक्ति किसी प्रामाणिक संस्करण से मिलान कर जाँची नहीं गई है।": "This line has not been checked word for word against a published edition.",
  "पंक्तियों की जाँच": "Verse review",
  "{done} / {total} पंक्तियाँ किसी प्रमाणिक संस्करण से मिलान कर जाँची गई हैं।": "{done} of {total} lines have been checked word for word against a published edition.",
  "अभी कोई पंक्ति जाँची नहीं गई। इसलिए हर पंक्ति के साथ “जाँच बाकी” का निशान दिखता है — ताकि कोई पाठ ग़लती से प्रामाणिक न समझ ले।": "No line has been checked yet. That is why every line carries a “Not checked yet” mark — so no text is mistaken for verified scripture.",
  "जो पंक्तियाँ किसी रचना से नहीं मिलीं, वे हटा दी गई हैं। अब सिर्फ़ वही दिखता है": "Lines that could not be matched to a known work have been removed. What remains",
  "जो स्रोत से जुड़ा हो — पर वह भी अभी अलिज्ञात स्रोत पर टिका है, तब तक जब तक जाँच न हो।": "is attributed to a source, but that attribution is still unconfirmed until someone checks it.",
  "पूरी सूची और जाँच का तरीका: CONTENT-REVIEW.md (रिपॉज़िटरी में)।": "The full list and how to check it: CONTENT-REVIEW.md (in the repository).",

  /* ---------- प्रसंग-निशान ---------- */
  "प्रारूप — जाँच बाकी": "Draft — not checked yet",

  /* ---------- पाठ-स्रोत ---------- */
  "{done} / {total} पंक्तियाँ अक्षर-अक्षर जाँची गई हैं।": "{done} of {total} lines have been checked word for word.",
  "पाठ कहाँ से आया": "Where the text comes from",
  "पूरा पाठ याद से नहीं, प्रकाशित स्रोत से उतारा गया है —": "The whole text was copied from a published source, not written from memory —",
  "(संस्करण:": "(edition:",
  "खोज की तारीख:": "Retrieved:",
  "क्या अभी बाकी है": "What is still outstanding",
  "पाठ:": "Text:",
  "तीन अलग स्रोतों से मिलाया गया; जहाँ अक्षर-भेद हैं वहाँ एक रूप चुना है। पूरी सूची CONTENT-REVIEW.md में है — विद्वान पाठक तय करें।": "cross-checked against three independent sources; where they differ, one reading was chosen. The full list is in CONTENT-REVIEW.md for a knowledgeable reader to settle.",
  "अर्थ:": "Meanings:",
  "पंक्ति जो कहती है उसी का सार लिखा है, पर यह मेरा अपना लेखन है और जाँचा नहीं गया।": "each one describes the lines it sits under, but these are my own words and have not been checked.",
  "इसीलिए हर पंक्ति के साथ “जाँच बाकी” दिखता है — कोई पाठ ग़लती से प्रामाणिक न समझ ले। जाँच पूरी होने पर यह निशान हट जाएगा।": "That is why every line carries a \"Not checked yet\" mark — so no text is taken for verified scripture. The mark disappears when the review is done.",
};
