/** English translation of every `t("…")` string. Hindi is the source language. */

export const EN: Record<string, string> = {
  "Bajrang को फ़ोन में लगाएँ": "Add Bajrang to your phone",
  "Safari → साझा करें → 'Add to Home Screen'": "Safari → Share → 'Add to Home Screen'",
  "एक टैप में खुलेगा, और रोज़ का संदेश भी आएगा।": "It opens in one tap, and the daily message comes too.",
  "लगाएँ": "Install",
  "ठीक है": "Okay",
  "दिन": "days",
  "भक्त": "Devotee",
  "तस्वीर सहेजी जा रही है — फिर WhatsApp में चुन लीजिए।": "The image is being saved — then choose it in WhatsApp.",
  "पॉपअप ब्लॉक है — तस्वीर सहेजें दबाएँ।": "A pop-up is in the way — press Save image.",
  "बजरंग कार्ड": "Bajrang card",
  "तस्वीर खुल गई — लंबे दबाएँ और 'Save Image' चुनें।": "The image has opened — press and hold, then choose 'Save Image'.",
  "बात कॉपी हो गई।": "The message has been copied.",
  "कॉपी नहीं हो सका।": "Could not copy.",
  "साप्ताहिक कार्ड": "Weekly card",
  "बंद करें": "Close",
  "बजरंग साप्ताहिक कार्ड": "Bajrang weekly card",
  "तैयार हो रहा है…": "Preparing…",
  "साझा करें": "Share",
  "WhatsApp पर भेजें": "Send on WhatsApp",
  "तस्वीर सहेजें": "Save the image",
  "तस्वीर खोलें": "Open the image",
  "PNG तस्वीर · 1080 × 1080 · कोई ऐप नहीं, सीधे WhatsApp": "PNG image · 1080 × 1080 · no app needed, straight to WhatsApp",
  "सिर्फ़ बात कॉपी करें": "Copy the message only",
  "जय बजरंगबली 🙏": "Jai Bajrang Bali 🙏",
  "पिछला महीना": "Previous month",
  "अगला महीना": "Next month",
  "मंगलवार / शनिवार": "Tuesday / Saturday",
  "पूजा पूरी": "Worship complete",
  "आज": "Today",
  "इस महीने पर लौटें": "Back to this month",
  "मंगलवार": "Tuesday",
  "— हनुमान जी का प्रिय दिन": " — Hanuman ji's beloved day",
  "शनिवार": "Saturday",
  "— संकष्टी, हनुमान जी के लिए समर्पित": " — purna, dedicated to Hanuman ji",
  "हर हफ़्ते दो बार संकल्प दोहराना आसान है — बस एक मिनट।": "Repeating your sankalp twice a week is easy — just one minute.",
  "स्रोत:": "Source:",
  "स्रोत देखें": "See the source",
  "अपने इलाके के पंचांग या धर्मप्रधान से भी तिथि जाँच लीजिए — पंचांग हर जगह एक जैसा नहीं होता।": "You can also check the date with your local Panchang or with your religious head — the Panchang is not the same everywhere.",
  "पंचांग": "Panchang",
  "आने वाला त्योहार": "Upcoming festival",
  "ये तिथियाँ": "These dates",
  "नया शुरुआत": "A new beginning",
  "विश्राम": "Pause",
  "जय श्री राम": "Jai Shri Ram",
  "आज की पूजा पूरी हो चुकी है। शाम को फिर मिलेंगे।": "Today's worship is complete. We will meet again this evening.",
  "आज का एक मिनट, हनुमान जी के साथ।": "One minute today, with Hanuman ji.",
  "कल फिर मिलेंगे। हनुमान जी आपका रक्षक हैं।": "We will meet again tomorrow. Hanuman ji is your protector.",
  "साप्ताहिक कार्ड साझा करें": "Share the weekly card",
  "आज की पूजा शुरू करें": "Begin today's worship",
  "साप्ताहिक कार्ड बनाएँ": "Create the weekly card",
  "आपके {n} दिन की साधना को साझा करें — एक तस्वीर, कुछ लोगों के लिए प्रेरणा बन जाएगी।": "Share your {n} days of sadhana — one picture can become inspiration for someone.",
  "विश्राम जारी है": "Pause is still on",
  "आज विश्राम का अंतिम दिन है। कल फिर सिलसिला यहीं से आगे बढ़ेगा।": "Today is the last day of the pause. Tomorrow the chain moves on from here.",
  "आज से फिर शुरू करें": "Begin again from today",
  "क्षमा बचा लेगी": "Grace will cover it",
  "बजरंग कथा": "The Bajrang Katha",
  "आज का संदेश": "Today's message",
  "आपका संकल्प": "Your sankalp",
  "इस हफ़्ते": "This week",
  "कुल पूजा": "Total worship",
  "सर्वश्रेष्ठ": "Best",
  "कल पूजा के बाद खुलेगा — प्रसंग {n}: {title}।": "Opens tomorrow after worship — passage {n}: {title}.",
  "रोज़ सुबह का संदेश चालू करें?": "Turn on the morning message?",
  "आपके चुने हुए समय पर हनुमान जी का वार याद दिला देंगे — हर दिन सिर्फ़ एक बार।": "We will remind you of Hanuman ji's arrival at the time you have chosen — only once a day.",
  "सेटिंग में जाएँ": "Go to Settings",
  "बाद में": "Later",
  "प्रसंग": "Passage",
  "कथा आरंभ": "The Katha begins",
  "पिछला प्रसंग": "Previous passage",
  "नया खुला प्रसंग": "New passage opened",
  "कल पूजा के बाद खुलेगा": "Opens tomorrow after worship",
  "सौ आठ प्रसंग पूरे हो गए। हनुमान जी का साथ अब भी साथ है 🙏": "All 108 passages are done. Hanuman ji's company is still with you 🙏",
  "रोज़ एक प्रसंग — पूजा के बाद ही खुलता है।": "One passage a day — it opens only after worship.",
  "सीख · ": "Lesson · ",
  "परंपरा में मतभेद · ": "A difference of tradition · ",
  "यह प्रसंग अभी लिखा जा रहा है। जिस दिन आपकी पूजा होगी, उसी दिन यह पूरा खुल जाएगा।": "This passage is still being written. On the day you worship, it will open fully.",
  "रोज़ एक मिनट": "One minute a day",
  "जय बजरंगबली": "Jai Bajrang Bali",
  "हर रोज़ सिर्फ़ एक मिनट — हनुमान चालीसा का एक पंक्ति, एक घंटी, और आपका संकल्प।": "Every day only one minute — one line of the Hanuman Chalisa, one bell, and your sankalp.",
  "कोई नाम पहले नहीं चाहिए, कोई खाता नहीं।": "No name is needed first, and no account either.",
  "पूजा शुरू करें 🙏": "Begin worship 🙏",
  "आपका नाम और संकल्प पूजा के बाद पूछा जाएगा।": "Your name and sankalp will be asked after the worship.",
  "आज की पूजा": "Today's worship",
  "आवाज़ के साथ, या बिना?": "With sound, or without?",
  "दोनों ही बराबर हैं। जो मन को भाए, वही चुनिए।": "Both are equal. Choose whatever your heart likes.",
  "आवाज़ के साथ": "With sound",
  "बिना आवाज़": "Without sound",
  "अभी नहीं": "Not now",
  "आवाज़ बंद करें": "Turn sound off",
  "आवाज़ चालू करें": "Turn sound on",
  "मैंने जप पूरा कर लिया": "I have completed the jap",
  "पूजा पूरी!": "Worship complete!",
  "हनुमान जी आपके साथ हैं": "Hanuman ji is with you",
  "आपकी लगातार पूजा": "Your steady worship",
  "कुल": "Total",
  "पूजा पूर्ण": "worships complete",
  "नया बैज!": "New badge!",
  "होम पर जाएँ": "Go to Home",
  "पूजा पूरी! 🙏": "Worship complete! 🙏",
  "हनुमान जी ने आपका नाम जान लिया। वे हर दिन आपको याद करेंगे।": "Hanuman ji has taken note of your name. He will remember you every day.",
  "आपका नाम": "Your name",
  "सहेजें": "Save",
  "रहने दीजिए": "Leave it",
  "एक संकल्प रख लीजिए": "Keep a sankalp",
  "यह कोई बात नहीं — पर रोज़ याद आएगा।": "It is nothing — but it will come back to you daily.",
  "जैसे: परीक्षा में पास होना": "For example: passing my exam",
  "रोज़ किस समय याद करें?": "What time should I remind you each day?",
  "याद दिलाना चालू करें": "Turn on the reminder",
  "बाद में करूँगा": "I will do it later",
  "आज का नया प्रसंग": "Today's new passage",
  "यह प्रसंग अभी लिखा जा रहा है।": "This passage is still being written.",
  "पूरा प्रसंग पढ़ें": "Read the full passage",
  "संकल्प": "Sankalp",
  "जैसे: परिवार का स्वास्थ्य": "For example: my family's health",
  "रद्द": "Cancel",
  "संकल्प बदलें": "Change sankalp",
  "अभी कोई संकल्प नहीं": "No sankalp yet",
  "एक छोटा इरादा रखिए — पढ़ाई, सेहत, परिवार, कुछ भी। रोज़ याद आएगा, और पूजा का मक़सद साफ़ हो जाएगा।": "Keep a small intention — studies, health, family, anything at all. It will come back to you daily, and the purpose of worship will become clear.",
  "जितनी लंबी स्ट्रीक, उतना चमकता दीवा": "The longer the streak, the brighter the diya",
  "अगला बैज: {m} दिन — {r} दिन और।": "Next badge: {m} days — {r} more days.",
  "108 दिन पूरे — आप परम भक्त हैं!": "108 days complete — you are a true devotee!",
  "कुछ दिन छूट जाएँ तो कोई बात नहीं — चिंता मत करो, फिर से शुरू करो 🙏": "If a few days are missed, it is nothing — do not worry, begin again 🙏",
  "लगातार दिन": "Days in a row",
  "बैज": "Badges",
  "हर दिन सुबह लग गया — ऐप बंद होने पर भी आएगा।": "It has been set for every morning — it will come even when the app is closed.",
  "इजाज़त मिली, पर समय नहीं लग सका।": "Permission was given, but the time could not be set.",
  "चालू — रोज़ सुबह संदेश आएगा।": "On — the message will come every morning.",
  "ब्राउज़र ने इजाज़त नहीं दी। फ़ोन की अलार्म में समय लगा लीजिए।": "The browser did not give permission. Set the time in your phone's alarm.",
  "https पर यह काम करता है। फ़ोन की अलार्म में समय लगा लीजिए।": "This works over https. Set the time in your phone's alarm as well.",
  "बंद कर दिया।": "It has been switched off.",
  "संदेश भेज दिया — देखिए।": "Message sent — have a look.",
  "संदेश नहीं जा सका।": "The message could not be sent.",
  "सेटिंग": "Settings",
  "सुरक्षित कनेक्शन नहीं है": "Not a secure connection",
  "अभी यह ऐप": "Right now this app",
  "पर चल रहा है। रोज़ का संदेश, फ़ोन में इंस्टॉल, और पूजा के दौरान स्क्रीन जली रखना — ये सब": "is running on. The daily message, install on your phone, and keeping the screen awake during worship — all of these need",
  "पर ही चलते हैं। पूजा और स्ट्रीक फिर भी ठीक से काम करेंगे।": "only. Worship and the streak will still work fine.",
  "असली जाँच के लिए ऐप को किसी https पते पर चलाएँ, या अपने फ़ोन के अलार्म में": "For a real test, run the app on an https address, or in your phone's alarm",
  "लगा लीजिए।": "have it set.",
  "याद दिलाना चालू रखें": "Keep the reminder on",
  "समय:": "Time:",
  "हर दिन": "Every day",
  "हर दिन लगा हुआ है।": "It is set for every day.",
  "ऐप बंद हो, फ़ोन बंद हो, कुछ भी हो — संदेश आ जाएगा।": "App closed, phone off, anything at all — the message will come.",
  "चालू है, पर समय नहीं लगा।": "It is on, but the time is not set.",
  "ऐप एक बार खोलिए, समय दोबारा चुनिए।": "Open the app once, choose the time again.",
  "ऐप बंद होने पर भी संदेश आएगा — यही Android ऐप की सबसे बड़ी बात है।": "The message comes even when the app is closed — this is the greatest thing about the Android app.",
  "Android से ठीक समय पर संदेश देने की अनुमति माँगी ज़रूरी है": "Android needs permission to deliver the message on time",
  "बिना इसके फ़ोन संदेश देर से दिखा सकता है।": "Without this, the phone may show the message late.",
  "Android सेटिंग्स में \"Alarms & reminders\" खोलिए।": "Open \"Alarms & reminders\" in Android Settings.",
  "अनुमति देने के लिए खोलें": "Open to give permission",
  "अपना समय चुनें": "Choose your time",
  "ऐसा संदेश आएगा": "A message like this will arrive",
  "अभी संदेश भेजकर देखें": "Send a test message now",
  "पहले ऊपर वाला स्विच चालू कीजिए — फिर यह संदेश जाँच सकेंगे।": "First turn on the switch at the top — then you can test this message.",
  "यह जाँच https पर ही हो पाएगी।": "This check will only work on https.",
  "यह संदेश Android के अलार्म पर लगा है — ऐप बंद होने पर भी आएगा। बस फ़ोन में": "This message is set on the Android alarm — it will come even when the app is closed. Just make sure",
  "से Bajrang को अनुमति दी हो तो ठीक समय आएगा।": "has permission on your phone, then it will arrive at the right time.",
  "यह PWA संस्करण है। ब्राउज़र बंद होने पर संदेश नहीं आ पाता, इसलिए भरोसेमंद नहीं।": "This is the PWA version. When the browser is closed the message does not arrive, so it cannot be relied on.",
  "Android ऐप": "Android app",
  "में यह हर दिन, ऐप बंद होने पर भी आता है — और वीडियो पर वही नाम, वही संदेश, वही स्ट्रीक चलती है। सबसे भरोसेमंद तरीका अभी भी:": "gives you this every day, even when the app is closed — and the same name, the same message, the same streak run on the video. The most dependable way is still:",
  "फ़ोन की अलार्म में भी": "an alarm in your phone at",
  "कभी-कभी बीमारी, यात्रा, या कोई मजबूरी होती है। ऐसे समय में डाँटने की बजाय रुक लीजिए — आपकी साधना जहाँ थी वहीं जुकी रहेगी। रुके हुए दिन छूटे नहीं गिने जाएँगे।": "Sometimes there is illness, travel, or some unavoidable reason. At such times, pause instead of blaming yourself — your sadhana stays joined where it was. Paused days will not be counted as missed.",
  "{d} दिन और। सिलसिला {s} दिन पर जुका हुआ है।": "{d} more days. Your chain is joined at {s} days.",
  "आज अंतिम दिन है।": "Today is the last day.",
  "विश्राम समाप्त। फिर शुरू करें 🙏": "Pause over. Begin again 🙏",
  "अभी लौटें": "Return now",
  "{d} दिन का विश्राम। आराम करिए।": "A pause of {d} days. Rest well.",
  "बाकी": "left",
  "हर {n} दिन लगातार पूजा करने पर एक क्षमा दिन अपने आप मिलता है। दिन छूट जाए तो यह अपने आप लग जाती है — इसलिए बार-बार सिलसिला नहीं टूटता।": "After {n} days of continuous worship, one grace day comes on its own. If a day is missed, it applies on its own — so your chain does not keep breaking.",
  "रात 3:00 बजे": "3:00 in the night, the day",
  "से शुरू होता है। रात 2 बजे की पूजा पहले दिन की गिनी जाती है — जैसे परंपरा में भी तिथि सूर्योदय से चलती है।": "begins then. Worship at 2 in the morning counts towards the previous day — as in tradition, the tithi also turns with sunrise.",
  "अभी पूजा का दिन है:": "Right now the worship day is:",
  "— घड़ी के हिसाब से": " — by the clock",
  "की रात है, पर पूजा का दिन पिछला ही चल रहा है।": "night, but the worship day is still the earlier one.",
  "पूजा के दौरान हल्का ॐ मंत्र": "a soft ॐ chant during worship",
  "बहुत धीमी, बहुत हल्की आवाज़ — साँस जैसी। पूजा के दौरान 🔊 बटन से भी बंद/चालू कर सकते हैं।": "A very slow, very soft sound — like a breath. During worship you can also turn it off and on with the 🔊 button.",
  "श्रीरामचरितमानस की भाषा में": "In the language of Shri Ramcharitmanas",
  "हिंदी में श्लोक उसी मूल रूप में रहते हैं": "in English the verses stay in their original form",
  "स्ट्रीक": "Streak",
  "सारी जानकारी सिर्फ़ आपके फ़ोन में सहेजी है — कोई अकाउंट नहीं, कोई सर्वर नहीं।": "All the information is stored only on your phone — no account, no server.",
  "रोज़ एक मिनट की पूजा, बस इतनी सी।": "One minute of worship a day, only that much.",
  "सारी जानकारी मिट जाएगी — नाम, संकल्प और स्ट्रीक। क्या आप नया शुरुआत करना चाहते हैं?": "All the information will be erased — your name, your sankalp and your streak. Do you want to start fresh?",
  "हाँ, नया शुरुआत करें": "Yes, start fresh",
  "नहीं": "No",
  "सब कुछ मिटाएँ": "Erase everything",
  "भाषा": "Language",
  "आज ही है! 🙏": "Today itself! 🙏",
  "• चैत्र पूर्णिमा (हनुमान जयंती): drikpanchang.com/vrats/purnimasidates.html": "• Chaitra Purnima (Hanuman Janm): drikpanchang.com/vrats/purnimasidates.html",
  "• राम नवमी: drikpanchang.com/hindu-festivals/rama-navami": "• Rama Navami: drikpanchang.com/hindu-festivals/rama-navami",
  "दिन बाकी": "days left",
  "पंक्ति": "Line",
  "जप": "Jap",
  "सेकंड बाकी": "seconds left",
  "हिंदी ⇄ बंगाला": "English ⇄ Bengali",
  "जाँच बाकी": "Not checked yet",
  "{done} / {total} पंक्तियाँ अक्षर-अक्षर जाँची गई हैं।": "{done} of {total} lines have been checked word for word.",
  "पाठ कहाँ से आया": "Where the text comes from",
  "पूरा पाठ याद से नहीं, प्रकाशित स्रोत से उतारा गया है —": "The whole text was copied from a published source, not written from memory —",
  "(संस्करण:": "(edition:",
  "खोज की तारीख:": "Retrieved:",
  "क्या अभी बाकी है": "What is still outstanding",
  "पाठ:": "Text:",
  "तीन अलग स्रोतों से मिलाया गया; जहाँ अक्षर-भेद हैं वहाँ एक रूप चुना है। पूरी सूची CONTENT-REVIEW.md में है — विद्वान पाठक तय करें।": "cross-checked against three independent sources; where they differ, one reading was chosen. The full list is in CONTENT-REVIEW.md for a knowledgeable reader to settle.",
  "अर्थ:": "Meanings:",
  "इसीलिए हर पंक्ति के साथ “जाँच बाकी” दिखता है — कोई पाठ ग़लती से प्रामाणिक न समझ ले। जाँच पूरी होने पर यह निशान हट जाएगा।": "That is why every line carries a \"Not checked yet\" mark — so no text is taken for verified scripture. The mark disappears when the review is done.",
  "{w} प्रसंग लिखे जा चुके हैं और हर एक का स्रोत दर्ज है, पर विद्वान पाठक की समीक्षा बाकी है। तब तक यह कथा आपके सामने नहीं आएगी।": "{w} episodes are written and each records its source, but a knowledgeable reader has not checked them yet. Until then the katha does not appear.",
  "जाँच बाकी — स्क्रीन पर रुका है": "Review pending — held back from the screen",
  "{w} प्रसंग लिखे गए हैं, पर विद्वान पाठक ने अभी एक भी देखा नहीं। इसलिए यहाँ अभी कुछ नहीं दिखाया जा रहा — जाँच पूरी होते ही प्रसंग अपने आप खुल जाएँगे।": "{w} episodes are written, but no knowledgeable reader has looked at any of them yet, so nothing is shown here — when the review is done the episodes open by themselves.",
  "हर प्रसंग का स्रोत दर्ज है — वाल्मीकि रामायण अथवा रामचरितमानस।": "Every episode records its source — the Valmiki Ramayana or the Ramcharitmanas.",
  "जाँच पूरी होने पर {r} और प्रसंग खुल जाएँगे — एक-एक करके।": "When the review is done, {r} more episodes will open, one at a time.",
  "रुके हुए प्रसंगों का शीर्षक भी अभी नहीं दिखाया जाता — जो कुछ जाँच से नहीं गुज़रा, वह प्रकाशित नहीं होगा।": "The titles of withheld episodes are not shown either — what has not passed review is not published.",
  "हर प्रसंग का स्रोत दर्ज है — वाल्मीकि रामायण या रामचरितमानस। जो कथा इन दोनों में नहीं मिलती, उसे “लोक-परंपरा” कहा गया है। विद्वान पाठक की समीक्षा पूरी होने से पहले कोई प्रसंग प्रकाशित नहीं होता।": "Every episode records its source — the Valmiki Ramayana or the Ramcharitmanas. Anything found in neither is marked \"folk tradition\". No episode is published before a knowledgeable reader has checked it.",
  "लोक-परंपरा — जाँच बाकी": "Folk tradition — review pending",
  "ग्रंथ-आधारित — जाँच बाकी": "From the texts — review pending",
  "कथा का हाल": "State of the katha",
  "{w} प्रसंग लिखे गए हैं, {p} प्रकाशित। जाँच पूरी न होने तक कथा स्क्रीन पर नहीं दिखती — न प्रसंग, न उनका शीर्षक।": "{w} episodes written, {p} published. Until the review is done the katha does not appear on the screen — not the episodes, not even their titles.",
  "हर प्रसंग पर दो बड़े ग्रंथों में से स्रोत दर्ज है; जो कथा वहाँ नहीं मिलती उसे “लोक-परंपरा” कहा गया है।": "Every episode records a source from the two great texts; anything found in neither is marked \"folk tradition\".",
  "जाँच बाकी — अभी जाँचा नहीं गया": "Review pending — not checked yet",
  "अर्थ अभी छिपा हुआ है — जाँच होने पर ही दिखेगा।": "meaning hidden until reviewed",
  "{m} / {n} जाँचे गए — बाकी छिपे हैं।": "{m} of {n} reviewed — the rest are hidden.",
  "पंक्ति स्क्रीन पर है, पर जोड़ा गया यह अर्थ अभी भरोसेमंद नहीं — इसलिए दिखाया नहीं जा रहा।": "The line is on screen, but this explanation is not yet trustworthy, so it is not shown.",
  "चालीसा यात्रा": "Chalisa yatra",
  "{r} / {n}": "{r} / {n}",
  "कल:": "Tomorrow:",
  "आज की पूजा के बाद चालीसा यात्रा शुरू होगी": "After today's worship the Chalisa yatra begins",
  "पहली इकाई:": "First unit:",
  "पूजा के बाद:": "After worship:",
  "चालीसा यात्रा पूरी": "Chalisa yatra complete",
  "सौ आठ प्रसंग पूरे, चालीस चौपाइयाँ के साथ।": "All one hundred and eight units, all forty chaupais.",
  "प्रसाद: जो मंत्र जाँचे गए, वे यहाँ मिलेंगे — अभी कोई जाँचा नहीं गया।": "Prasad: reviewed mantras will appear here — none has been reviewed yet.",
  "चालीसा यात्रा: {r} / {n}": "Chalisa yatra: {r} / {n}",
  "डाउनलोड बैकअप": "Download backup",
  "बैकअप आयात करें": "Import backup",
  "कभी नहीं": "never",
  "बैकअप फ़ाइल तैयार है।": "Backup file is ready.",
  "फ़ाइल पढ़ी नहीं जा सकी।": "That file could not be read.",
  "फ़ाइल पढ़ी नहीं जा सकी — शायद यह अधूरी है।": "That file could not be read - it may be incomplete.",
  "आपके {n} दिन की साधना सुरक्षित करें — एक बैकअप फ़ाइल डाउनलोड करें।": "Secure your {n} days of practice - download a backup file.",
  "सब कुछ सिर्फ़ इसी फ़ोन में है। एक फ़ाइल डाउनलोड कर लीजिए — फ़ोन बदलने पर उसे वहीं वापस ला सकेंगे।": "Everything lives only on this phone. Download a file and you can bring it back on a new phone.",
  "आख़िरी बैकअप:": "Last backup:",
  "(drikpanchang.com) से ली गई हैं। भारत के पंचांग के हिसाब से चाँद वाले त्योहार एक दिन ऊपर-नीचे हो सकते हैं, और दूसरे देशों में यही तिथि एक दिन पहले पड़ सकती है। अपने इलाके की पंचांग से मिलाकर ऊपर वाली तारीख बदल दीजिए।": " (drikpanchang.com). Indian panchangas put lunar festivals a day either way, and the same date falls a day earlier in other countries. Match it against your local panchang and change the date above if needed.",
  "फ़ोन बदलें या डेटा मिटे, तो यह सब चला जाएगा। बैकअप से वापस आ जाता है।": "If the phone changes or the data is cleared, all of this is gone. A backup brings it back.",
  "बैकअप लें": "Take a backup",
  "यहाँ सिर्फ़ गिनती है — पूजा कितनी हुई, कब छूटी, कार्ड कितनी बार बना। न कोई नाम, न कोई सर्वर, न कोई भेजा हुआ आँकड़ा।": "Counts only - how many prayers, when one was skipped, how many cards were made. No name, no server, nothing is sent anywhere.",
  "अभी कोई गिनती नहीं।": "Nothing counted yet.",
  "यह गिनती मिटाएँ": "Clear these counts",
  "पूरी साधना मिटाएँ": "Clear all practice data",
  "हनुमान जी का दिन": "Hanuman's day",
  "{d} दिन और आराम। आपकी {s} दिन की साधना जहाँ थी वहीं सुरक्षित है।": "{d} more days of rest. Your {s} days of practice stay safe where they are.",
  "अर्थ अभी जाँचा नहीं गया — इसलिए यहाँ नहीं दिखाया जा रहा।": "The meaning has not been checked yet, so it is not shown.",
  "{m} दिन छूट गए हैं, पर आपके पास {g} क्षमा दिन हैं। आज पूजा कीजिए — सिलसिला टूटेगा नहीं।": "{m} days were missed, but you have {g} grace days. Pray today and the streak holds.",
  "{m} दिन बीत गए — कोई बात नहीं। हनुमान जी आज भी आपके साथ हैं। एक मिनट से ही सब शुरू हो जाता है।": "{m} days have passed - that is all. Hanuman is with you still, and one minute is enough to begin again.",
  "{n} क्षमा दिन बाकी": "{n} grace days left",
  "इस हफ़्ते अभी कोई पूजा नहीं": "No prayer this week yet",
  "इस हफ़्ते एक पूजा": "One prayer this week",
  "आज की पूजा पूरी": "Today's prayer is complete",
  "रुके हुए दिन छूटे नहीं गिने जाएँगे।": "The paused days will not count as missed.",
  "चिंता मत करो, फिर से शुरू करो": "Do not worry, begin again",
  "हर {n} दिन की साधना पर एक क्षमा दिन मिलता है (ज़्यादा से ज़्यादा {m})।": "One grace day for every {n} days of practice (up to {m}).",
  "जय बजरंगबली — प्रेम और अनुशासन, रोज़ एक मिनट": "",

  "इस हफ़्ते {n} पूजा": "{n} prayers this week",
  "कथा जाँच के बाद खुलेगी": "The katha opens after review",
  "जाँच की स्थिति देखें": "See the review status",
  "सौ आठ प्रसंग पूरे": "All 108 units",
  "आप पूरी कथा सुन चुके हैं। हनुमान जी का साथ सदा के लिए बना रहे।": "You have heard the whole katha",
  "कथा दोबारा पढ़ें": "Read the katha again",
  "कथा पढ़ें": "Read the katha",
  "शुभ रात्रि 🙏": "Good night",
  "शुभ प्रभात 🙏": "Good morning",
  "नमस्कार 🙏": "Namaskar",
  "शुभ संध्या 🙏": "Good evening",
  "…": "…",
  "हनुमान जी का वार है — आज की पूजा 1 मिनट में पूरी करो": "Hanuman has come - finish today's prayer in 1 minute",
  "बजरंग": "Bajrang",
  "हर दिन 1 मिनट की हनुमान पूजा": "1 minute of Hanuman puja every day",
  "मैंने {p} लगातार हनुमान चालीसा की": "I have read the Hanuman Chalisa for {p} in a row",
  "संकल्प:": "Resolve:",
  "चलो हनुमान जी के साथ जियें": "Let us live with Hanuman",
  "मैंने {p} लगातार हनुमान चालीसा की 🙏": "I have read the Hanuman Chalisa for {p} in a row",
  "आज का स्ट्रीक:": "Today's streak:",
  "मेरा संकल्प:": "Resolve:",
  "आप भी रोज़ 1 मिनट हनुमान जी के साथ बिताइए — Bajrang app": "each day - Bajrang app",
  "বাংলায় শ্লোক দেবনাগরিতেই থাকবে": "In Bengali, the verses",
  "English screen, but the verses stay in the original Devanagari": "the verses stay",
  ")": ")",
  "हनुमान जी के दिन": "Hanuman's days",
  "त्योहार की तिथि": "Festival dates",
  "दीवे की चमक": "Glow of the lamp",
  "आपकी साधना": "Your practice",
  "रोज़ का संदेश": "Daily message",
  "क्षमा दिन": "Grace days",
  "दिन की शुरुआत": "Start of the day",
  "पूजा की आवाज़": "Sound of worship",
  "पंक्तियों की जाँच": "Verse review",
  "मेरा डेटा": "My data",
  "बैकअप": "Backup",
  "ऐप के बारे में": "About the app",
  "अर्थ अभी जाँचा नहीं गया": "Meaning not checked yet",
  "पाठ स्रोत से लाया गया है, पर अक्षर-अक्षर जाँच बाकी है": "Text taken from a cited source; letter-by-letter check still pending",
  "आज की पूजा के बाद यात्रा आगे बढ़ेगी — कुल {n} इकाइयाँ।": "After today's prayer the yatra advances - {n} units in all",
};
